[package]
name = "empire-client"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
crate-type = ["lib", "staticlib"]
[dependencies]
empire-sim.workspace = true
empire-content.workspace = true
empire-ai.workspace = true
serde_json.workspace = true
bevy = { version = "=0.16.1", default-features = false, features = ["std", "async_executor", "bevy_asset", "bevy_color", "bevy_core_pipeline", "bevy_render", "bevy_sprite", "bevy_text", "bevy_ui", "bevy_window", "bevy_winit", "bevy_log", "default_font", "multi_threaded", "png", "x11"] }

